Build env: Regenerate aclocal.m4 and rename configure.in
adfinis-forks/check_hpasm pull request #2
Opened 2017-12-04 07:41 UTC by matsimon

- Regenerate aclocal.m4 with aclocal to make automake 1.15 happy.
- Rename configure.in (deprecated) into .ac to make autoconf happy
  I didn't find where exactly they started to consider it deprecated.

2017-12-15 10:06 UTC, matsimon commented
I've renamed the pull request to add required build instructions to make it reliably build (for me...).

autoreconf as a wrapper seems to be the way to go, since it executes automake, aclocal, autoheader, automake and whatnot multiple times to make $magic happen. It's more consistent than trying to use individual tools in the right order. After reading some manpages I concluded, this was likely the better option.

The README wasn't renamed updated to markdown although it is in Markdown syntax, since somewhere in the make instructions README is actually used at some point and will fail if we only rename the file.

Let me know what you think about this. Not perfect, but I don't think it's worth the troubly updating aclocal and whatnot since to many systems have older versions of  said GNU tools available.
(remember I managed to break building on CentOS 7) Better play safe and don't attempt breaking things I don't fully understand yet.

2017-12-15 10:27 UTC, keachi requested changes
Don't copy the README to README.md as we don't want the same file twice.

Build instructions work on CentOS 7 and Debian 9.

2017-12-18 07:35 UTC, matsimon commented
Should be fixed, thanks, mumble *shake fist* didn't do that on a clean branch :)

2017-12-18 07:59 UTC, keachi approved these changes

2017-12-18 07:59 UTC, merged